### ISSUE TITLE
how to you install this?

### ISSUE THREAD

**Issue by Perfectgoose6573** [ajanata/gotogen-dbg#1]
how do you install this? and can i use this for other projects to?

**Comment by ajanata** [comment]
This is somewhat nontrivial to get going, since you need the C development stack for glib for your particular operating system. A good starting point is [https://github.com/gotk3/gotk3/wiki](the gotk3 wiki).

That said, this isn't particularly stable (it crashes for me randomly fairly often on both Windows and Linux), and has proven to be of limited utility while I've been working on the main gotogen software. You're welcome to use this as you see fit according to the terms of the [license](https://github.com/ajanata/gotogen-simulator/blob/main/LICENSE), if it's useful.

One of these days I do want to clean up this collection of repos and improve the documentation, now that I have it in a mostly working and usable state.
